### ISSUE TITLE
When terminating a cluster, the end_date should be updated.

### ISSUE THREAD

**Issue by maurodoglio** [mozilla/telemetry-analysis-service#264] opened 2017-02-27 13:37 UTC
Looking at the atmo data on STMO I found out that almost all the clusters have the same duration (24h), so there's no way to know the exact amount of cpu hours used.

**Comment by jezdez** [comment] 2017-03-07 16:31
Hm, `end_date` defines the time until when the cluster should be automatically EOL'd, but we don't offer setting that via the UI, so it will by design always be 24 hours by default. I'm trying to understand what you try to do with the query on STMO, are you looking for the outliers that are *not* killed exactly after 24 hours?

**Comment by maurodoglio** [comment] 2017-03-07 17:06
A cluster can be either killed manually or by the scheduler. I think we should update the end_date in the former case, to reflect the actual termination date of the cluster. This will let me tell how long  each cluster has been running for, which is not possible at the moment.

**Comment by rafrombrc** [comment] 2017-05-10 18:30
This is best done by getting the info from the stream rather than the current state-based job status, blocked by #332.

**Comment by rafrombrc** [comment] 2017-05-17 18:32
Turns out #332 isn't a hard blocker, which is good bc #332 will be done later than originally intended. Moving to m2.

**Comment by jezdez** [comment] 2017-05-24 11:31
Now that #487 is merged this is fixed.

**Closed by jezdez** 2017-05-24 11:31 UTC
