### ISSUE TITLE
Job kicked off twice yesterday

### ISSUE THREAD

**Issue by sunahsuh** [mozilla/telemetry-analysis-service#417] opened 2017-05-04 11:03 UTC
I got a failure email last night for my txp-install-uninstall-events job but looking at the cluster/job list it looks like it's because the job was queued twice (and both ran at the same time.)

**Comment by jezdez** [comment] 2017-05-04 11:52
@sunahsuh Yeah, it seems as if the celerybeat isn't behaving correctly, even though it has a distributed lock to prevent duplicated tasks to spawn. I'm investigating this right now as well for stage where the the new scheduling code landed.

**Comment by jezdez** [comment] 2017-05-04 11:52
I think this is related and possibly a dup of #353.

**Comment by jezdez** [comment] 2017-05-05 08:39
I've opened https://github.com/sibson/redbeat/issues/50 to fix this issue, in which the config code of RedBeat incorrectly read the "max_loop_interval" setting due to [a drastic change of setting names in Celery 4.0](http://docs.celeryproject.org/en/latest/whatsnew-4.0.html#v400-upgrade-settings) and essentially return 0. The problem is that this value is used for the [timeout of the distributed lock](https://github.com/sibson/redbeat/blob/3f7e97c81411656ed52e2863d4de34983fdd3925/redbeat/schedulers.py#L42) that prevents the beat process to schedule multiple times instead of just once per cluster. Given our way of deployment on AWS we're running the scheduler in multiple containers to not create a bottleneck.

**Comment by sunahsuh** [comment] 2017-05-05 11:24
Jezdez++ for mad debugging skills, damn

**Comment by jezdez** [comment] 2017-05-05 13:05
@sunahsuh Thanks! It's been a particularly _fun_ rabbit hole.

**Comment by jezdez** [comment] 2017-05-05 13:05
#421 makes uses of the patched version of RedBeat.

**Closed** 2017-05-11 08:07 UTC
Labels: review
