### ISSUE TITLE
No Master Address Listed In Fields

### ISSUE THREAD

**Issue by cameres** [mozilla/telemetry-analysis-service#281] opened 2017-03-01 22:41 UTC
I had the following issue on Monday, but haven't had the issue since, so I'm unsure if it's worth investigating:

Weird occurrence today where ATMO states that the spark cluster is waiting (had been launched approximately 45 minutes earlier), but doesn't display the hostname in the "Access" Fields, etc (see attachment screenshot). However, I was able to see the address after terminating the instance (additional screenshot). I tried launching another cluster (on same day of issue) after the issues shown above, but had the same results.

<img width="1132" alt="screen shot 2017-02-27 at 12 38 02 pm" src="https://cloud.githubusercontent.com/assets/5957933/23484751/18f1b4c2-fe8d-11e6-801b-8a7c633b51a8.png">

<img width="221" alt="screen shot 2017-02-27 at 12 39 09 pm" src="https://cloud.githubusercontent.com/assets/5957933/23484762/281a1f34-fe8d-11e6-873d-127b61e5c2d2.png">

**Comment by jezdez** [comment] 2017-03-06 14:22
Thanks for the report @cameres! This is a duplicate of #272

**Closed by jezdez** 2017-03-06 14:22 UTC
